FROM golang:1.7 as builder

WORKDIR /go/src/app

COPY /go.mod .
COPY /rocks.go .

RUN go build -ldflags "-s -w" -o /go/dist/app/codeRocks


FROM scratch

COPY --from=builder /go/dist/app /go/app
WORKDIR /go/app
ENTRYPOINT [ "./codeRocks" ]
